
Responses:
  - standings
  - patrick teams
  - jack teams
  - jordan teams
  - nathan teams
  - all teams
  - nfl bot help
  - my teams

espn_url: https://www.espn.com/nfl/standings/_/season/2021
season: 2021
