RESPONSES:
  - standings
  - patrick teams
  - jack teams
  - jordan teams
  - nathan teams
  - all teams
  - nfl bot help
  - my teams
  - standings right now

# Switch this config to False for most of the year - only use at draft time
DRAFT_CONFIG:
  draft_enabled: False
  custom_draft_order:
    - "9957374"
    - "13529310"
    - "13038894"
    - "17900487"
  num_teams: 32
  sql_flavor: postgres

BASE_CONFIG:
  season: "2023"
  nfl_season_start_date: "09/05/2023"
  owners:
    - Jack Francis
    - Jordan Holland
    - Nathan Lee
    - Patrick Cooper
  group_id: "7867099"
  dev_group_id: "59458329"
  # Online App Configs
  test_url: https://nfl-groupme-bot.onrender.com
  prod_url: https://nfl-groupme-flask-bot.onrender.com
  grid_filepath: ./NFL_Schedule_Data/2023_NFL_Schedule_Grid.csv
  weekly_matchups_filepath: ./NFL_Schedule_Data/2023_weekly_matchups.csv