Baltimore Ravens:
  - BAL
Tennessee Titans:
  - TEN
New York Jets:
  - NYJ
Miami Dolphins:
  - MIA
New England Patriots:
  - NE
Atlanta Falcons:
  - ATL
San Francisco 49ers:
  - SF
Arizona Cardinals:
  - ARI
Jacksonville Jaguars:
  - JAC
Kansas City Chiefs:
  - KC
Las Vegas Raiders:
  - LV
Detroit Lions:
  - DET
Minnesota Vikings:
  - MIN
Chicago Bears:
  - CHI
Dallas Cowboys:
  - DAL
Seattle Seahawks:
  - SEA
Cincinnati Bengals:
  - CIN
Cleveland Browns:
  - CLE
Houston Texans:
  - HOU
Denver Broncos:
  - DEN
Green Bay Packers:
  - GB
New Orleans Saints:
  - "NO"
Philadelphia Eagles:
  - PHI
New York Giants:
  - NYG
Pittsburgh Steelers:
  - PIT
Indianapolis Colts:
  - IND
Buffalo Bills:
  - BUF
Los Angeles Chargers:
  - LAC
Carolina Panthers:
  - CAR
Tampa Bay Buccaneers:
  - TB
Washington Commanders:
  - WAS
Los Angeles Rams:
  - LAR